export const actionTypes = {
  //popular
  FETCH_POPULAR_REQUEST: "FETCH_POPULAR_REQUEST",
  FETCH_POPULAR_SUCCESS: "FETCH_POPULAR_SUCCESS",
  FETCH_POPULAR_FAILURE: "FETCH_POPULAR_FAILURE",

  FETCH_SIMILAR_REQUEST: "FETCH_SIMILAR_REQUEST",
  FETCH_SIMILAR_SUCCESS: "FETCH_SIMILAR_SUCCESS",
  FETCH_SIMILAR_FAILURE: "FETCH_SIMILAR_FAILURE",

  FETCH_TOP_RATED_REQUEST: "FETCH_TOP_RATED_REQUEST",
  FETCH_TOP_RATED_SUCCESS: "FETCH_TOP_RATED_SUCCESS",
  FETCH_TOP_RATED_FAILURE: "FETCH_TOP_RATED_FAILURE",

  FETCH_UPCOMING_REQUEST: "FETCH_UPCOMING_REQUEST",
  FETCH_UPCOMING_SUCCESS: "FETCH_UPCOMING_SUCCESS",
  FETCH_UPCOMING_FAILURE: "FETCH_UPCOMING_FAILURE",

  FETCH_DETAIL_REQUEST: "FETCH_DETAIL_REQUEST",
  FETCH_DETAIL_SUCCESS: "FETCH_DETAIL_SUCCESS",
  FETCH_DETAIL_FAILURE: "FETCH_DETAIL_FAILURE",

  FETCH_SEARCH_REQUEST: "FETCH_SEARCH_REQUEST",
  FETCH_SEARCH_SUCCESS: "FETCH_SEARCH_SUCCESS",
  FETCH_SEARCH_FAILURE: "FETCH_SEARCH_FAILURE",

  FETCH_VIDEOS_REQUEST: "FETCH_VIDEOS_REQUEST",
  FETCH_VIDEOS_SUCCESS: "FETCH_VIDEOS_SUCCESS",
  FETCH_VIDEOS_FAILURE: "FETCH_VIDEOS_FAILURE",
};

export const actionTvTypes = {
  FETCH_TV_REQUEST: "FETCH_TV_REQUEST",
  FETCH_TV_SUCCESS: "FETCH_TV_SUCCESS",
  FETCH_TV_FAILURE: "FETCH_TV_FAILURE",
};

export const actionUsers = {
  FETCH_RQ_TOKEN_REQUEST: "FETCH_RQ_TOKEN_REQUEST",
  FETCH_RQ_TOKEN_SUCCESS: "FETCH_RQ_TOKEN_SUCCESS",
  FETCH_RQ_TOKEN_FAILURE: "FETCH_RQ_TOKEN_FAILURE",

  SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  SIGN_IN_WITH_GOOGLE: "SIGN_IN_WITH_GOOGLE",
};
