export const actionTypes = {
  //popular
  FETCH_MOVIE_REQUEST: "FETCH_MOVIE_REQUEST",
  FETCH_MOVIE_SUCCESS: "FETCH_MOVIE_SUCCESS",
  FETCH_MOVIE_FAILURE: "FETCH_MOVIE_FAILURE",

  FETCH_SIMILAR_REQUEST: "FETCH_SIMILAR_REQUEST",
  FETCH_SIMILAR_SUCCESS: "FETCH_SIMILAR_SUCCESS",
  FETCH_SIMILAR_FAILURE: "FETCH_SIMILAR_FAILURE",

  FETCH_DETAIL_REQUEST: "FETCH_DETAIL_REQUEST",
  FETCH_DETAIL_SUCCESS: "FETCH_DETAIL_SUCCESS",
  FETCH_DETAIL_FAILURE: "FETCH_DETAIL_FAILURE",
};

export const actionTvTypes = {
  FETCH_TV_REQUEST: "FETCH_TV_REQUEST",
  FETCH_TV_SUCCESS: "FETCH_TV_SUCCESS",
  FETCH_TV_FAILURE: "FETCH_TV_FAILURE",
};
