export const actionTypes = {
  //popular
  FETCH_POPULAR_REQUEST: "FETCH_POPULAR_REQUEST",
  FETCH_POPULAR_SUCCESS: "FETCH_POPULAR_SUCCESS",
  FETCH_POPULAR_FAILURE: "FETCH_POPULAR_FAILURE",

  FETCH_SIMILAR_REQUEST: "FETCH_SIMILAR_REQUEST",
  FETCH_SIMILAR_SUCCESS: "FETCH_SIMILAR_SUCCESS",
  FETCH_SIMILAR_FAILURE: "FETCH_SIMILAR_FAILURE",

  FETCH_TOP_RATED_REQUEST: "FETCH_TOP_RATED_REQUEST",
  FETCH_TOP_RATED_SUCCESS: "FETCH_TOP_RATED_SUCCESS",
  FETCH_TOP_RATED_FAILURE: "FETCH_TOP_RATED_FAILURE",

  FETCH_UPCOMING_REQUEST: "FETCH_UPCOMING_REQUEST",
  FETCH_UPCOMING_SUCCESS: "FETCH_UPCOMING_SUCCESS",
  FETCH_UPCOMING_FAILURE: "FETCH_UPCOMING_FAILURE",

  FETCH_DETAIL_REQUEST: "FETCH_DETAIL_REQUEST",
  FETCH_DETAIL_SUCCESS: "FETCH_DETAIL_SUCCESS",
  FETCH_DETAIL_FAILURE: "FETCH_DETAIL_FAILURE",

  FETCH_SEARCH_REQUEST: "FETCH_SEARCH_REQUEST",
  FETCH_SEARCH_SUCCESS: "FETCH_SEARCH_SUCCESS",
  FETCH_SEARCH_FAILURE: "FETCH_SEARCH_FAILURE",
};

export const actionTvTypes = {
  FETCH_TV_REQUEST: "FETCH_TV_REQUEST",
  FETCH_TV_SUCCESS: "FETCH_TV_SUCCESS",
  FETCH_TV_FAILURE: "FETCH_TV_FAILURE",
};
